# Generated by Django 3.2.7 on 2022-01-10 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookingapp', '0002_alter_userbooking_phone_num'),
    ]

    operations = [
        migrations.AddField(
            model_name='userbooking',
            name='gender',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
