# Generated by Django 3.2.7 on 2022-01-12 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookingapp', '0004_userbooking_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userbooking',
            name='image',
            field=models.CharField(max_length=500, null=True),
        ),
    ]
