# Generated by Django 3.2.7 on 2022-01-12 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookingapp', '0005_alter_userbooking_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userbooking',
            name='dob',
            field=models.DateField(blank=True, null=True),
        ),
    ]
