# Generated by Django 3.2.7 on 2022-01-12 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookingapp', '0006_alter_userbooking_dob'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userbooking',
            name='phone_num',
            field=models.BigIntegerField(null=True),
        ),
    ]
