# Generated by Django 3.2.7 on 2022-01-21 14:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bookingapp', '0008_auto_20220119_0510'),
    ]

    operations = [
        migrations.CreateModel(
            name='bookform',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fname', models.CharField(max_length=15)),
                ('lname', models.CharField(max_length=15)),
                ('checkin', models.DateField(blank=True, null=True)),
                ('checkout', models.DateField(blank=True, null=True)),
                ('address', models.CharField(max_length=200)),
                ('country', models.CharField(max_length=20)),
                ('state', models.CharField(max_length=20)),
                ('city', models.CharField(max_length=20)),
                ('pincode', models.BigIntegerField()),
                ('phone', models.BigIntegerField()),
                ('email', models.EmailField(max_length=254)),
                ('roomid', models.CharField(max_length=15)),
                ('propertyid', models.CharField(max_length=15)),
                ('userss', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='bookingapp.userbooking')),
            ],
        ),
    ]
