# Generated by Django 3.2.7 on 2021-12-29 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='owners',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=25)),
                ('email', models.EmailField(max_length=254)),
                ('dob', models.DateField()),
                ('phone_num', models.BigIntegerField()),
                ('password', models.CharField(max_length=10)),
            ],
        ),
    ]
