# Generated by Django 3.2.7 on 2022-01-11 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ownerapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='owners',
            name='gender',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
