# Generated by Django 3.2.7 on 2022-01-12 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ownerapp', '0002_owners_gender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='owners',
            name='id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
    ]
