# Generated by Django 3.2.7 on 2022-01-13 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ownerapp', '0004_ownerproperties'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ownerproperties',
            name='uploadby',
            field=models.CharField(max_length=6, null=True),
        ),
    ]
