# Generated by Django 3.2.7 on 2022-01-15 08:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ownerapp', '0006_auto_20220113_0423'),
    ]

    operations = [
        migrations.AddField(
            model_name='ownerproperties',
            name='propertyimage',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.CreateModel(
            name='roomproperty',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('roomtype', models.CharField(max_length=20, null=True)),
                ('capacity', models.IntegerField()),
                ('price', models.IntegerField()),
                ('status', models.CharField(max_length=20, null=True)),
                ('property_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='ownerapp.ownerproperties')),
            ],
        ),
    ]
