# Generated by Django 3.2.7 on 2022-01-17 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ownerapp', '0009_alter_ownerproperties_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='roomproperty',
            name='roomnumber',
            field=models.IntegerField(null=True),
        ),
    ]
