# Generated by Django 3.2.7 on 2022-01-17 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ownerapp', '0010_roomproperty_roomnumber'),
    ]

    operations = [
        migrations.AlterField(
            model_name='roomproperty',
            name='roomnumber',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
