# Generated by Django 3.2.7 on 2022-01-18 06:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ownerapp', '0011_alter_roomproperty_roomnumber'),
    ]

    operations = [
        migrations.AddField(
            model_name='roomproperty',
            name='owner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='ownerapp.owners'),
        ),
    ]
