# Generated by Django 3.2.7 on 2022-01-19 12:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ownerapp', '0013_auto_20220117_2329'),
    ]

    operations = [
        migrations.CreateModel(
            name='ownercontactus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25)),
                ('email', models.EmailField(max_length=254)),
                ('subject', models.CharField(max_length=20, null=True)),
                ('message', models.CharField(max_length=200, null=True)),
                ('owner', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='ownerapp.owners')),
            ],
        ),
    ]
