# Generated by Django 3.2.7 on 2022-01-20 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='admin1',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=25)),
                ('email', models.EmailField(max_length=254)),
                ('dob', models.DateField()),
                ('phone_num', models.BigIntegerField()),
                ('password', models.CharField(max_length=10)),
                ('gender', models.CharField(max_length=20, null=True)),
            ],
        ),
    ]
