# Generated by Django 3.2.7 on 2022-01-20 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='admin1',
            name='image',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
