# Generated by Django 3.2.7 on 2022-01-20 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0002_admin1_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='admin1',
            name='image',
            field=models.CharField(max_length=2000, null=True),
        ),
    ]
