# Generated by Django 3.2.7 on 2022-01-20 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0003_alter_admin1_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='blogs',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('categories', models.CharField(max_length=30)),
                ('writtenby', models.CharField(max_length=50)),
                ('image', models.CharField(max_length=400)),
                ('description', models.CharField(max_length=2000)),
            ],
        ),
    ]
